name: strings-action
description: "Functions for strings."

branding:
  icon: file-text
  color: black

inputs:
  value:
    description: "Value that the substring will be obtained from."
    required: true
  func_name:
    description: "Function name to use."
    required: true
  output_name:
    description: "The name of the output variable."
    required: true
    default: result

  start:
    description: "substring() : Start Index( Inclusive )"
    required: false
  end:
    description: "substring() : End Index( Exclusive )"
    required: false

  replace_str:
    description: "replace() : Old string"
    required: false
  replace_with_str:
    description: "replace(), replace_regex() : New string"
    required: false

  seperator:
    description: "split_str() : Seperator"
    required: false

  replace_regex:
    description: "replace_regex() : Regex"
    required: false

  index_of_str:
    description: "index_of() : String to find"
    required: false

runs:
  using: node16
  main: dist/index.js
